# shellcheck shell=bash
# Appended to a prelude generated by package.nix, which defines:
#   default_prefix, default_grab_pointer, packaged_proton, installer,
#   and apply_package_environment.

umask 077
# Globs below rely on unmatched patterns expanding to nothing.
shopt -s nullglob extglob

show_help() {
  cat <<EOF
Usage: eve-online [--install | --help] [launcher arguments...]

  (default)  Run CCP's official EVE Online launcher
  --install  Install dependencies and the CCP launcher
  --help     Show this help

Environment:
  EVE_WINEPREFIX    Absolute path to override the configured Wine prefix
  PROTONPATH        Override the configured Proton installation
  EVE_LAUNCHER_EXE  Absolute path to the launcher executable
  EVE_GRAB_POINTER  Y/N to set Wine's GrabPointer; empty leaves it unchanged

  Default prefix: $default_prefix

Close the launcher and all EVE clients before running --install.
EOF
}

# Runs a tool from the prefix's system32. The run verb avoids waiting for
# other Wine processes to exit.
run_wine_tool() {
  local tool="$1"
  shift
  PROTON_VERB=run umu-run "C:\\windows\\system32\\$tool.exe" "$@"
}

# Prints the subtree under KEY with carriage returns removed. KEY must exist
# in every prefix: then any failure is a real error, and a missing subkey or
# value is simply absent from the listing. reg.exe's exit status and messages
# cannot tell a missing key apart from other failures. Extra arguments, such
# as /reg:32, are passed to reg.exe.
list_registry_tree() {
  local key="$1" output
  shift
  # Proton logging redirects reg.exe's output to a file. Disable it only
  # for queries whose output we parse, preserving logging for the app.
  if ! output="$(PROTON_LOG=0 run_wine_tool reg query "$key" /s "$@")"; then
    printf 'Unable to read %s in %s\n' "$key" "$WINEPREFIX" >&2
    return 1
  fi
  printf '%s\n' "${output//$'\r'/}"
}

# Succeeds if a registry listing contains KEY or any of its subkeys. Keys
# must use full root names, such as HKEY_CURRENT_USER, as reg.exe prints them.
registry_has_key() {
  local listing=$'\n'"${1,,}"$'\n' key="${2,,}"
  [[ "$listing" == *$'\n'"$key"$'\n'* || "$listing" == *$'\n'"$key\\"* ]]
}

# Prints the data of VALUE directly under KEY in a registry listing, or
# nothing if it is absent.
registry_value() {
  local line in_key=0
  local key="${2,,}" value="${3,,}"
  local value_pattern='^    (.+)    REG_[A-Z0-9_]+    (.*)$'
  while IFS= read -r line; do
    if [[ "$line" != ' '* ]]; then
      # Header lines start each key's block; blank lines end it.
      in_key=0
      [[ "${line,,}" != "$key" ]] || in_key=1
    elif (( in_key )) && [[ "$line" =~ $value_pattern && "${BASH_REMATCH[1],,}" == "$value" ]]; then
      printf '%s\n' "${BASH_REMATCH[2]}"
      return
    fi
  done <<<"$1"
}

newest_by_version() {
  printf '%s\n' "$@" | sort --version-sort | tail -n 1
}

# Succeeds if a .NET Framework Release value is at least 4.5.2 (379893),
# which the CCP installer requires.
is_supported_dotnet_release() {
  [[ "$1" =~ ^0x([[:xdigit:]]{1,8})$ ]] && (( 16#${BASH_REMATCH[1]} >= 379893 ))
}

# Prints the Proton directory UMU runs. PROTONPATH can be a UMU release name
# such as GE-Proton, which only UMU can resolve, so ask a process it started.
resolve_proton_dir() {
  local resolved
  if [[ -d "$PROTONPATH" ]]; then
    realpath -e -- "$PROTONPATH"
    return
  fi

  resolved="$(PROTON_LOG=0 run_wine_tool cmd /c echo '%PROTONPATH%')" || return
  resolved="$(printf '%s\n' "${resolved//$'\r'/}" | tail -n 1)"
  if [[ "$resolved" != /* || ! -d "$resolved" ]]; then
    printf 'Unable to resolve the Proton directory UMU uses for PROTONPATH=%s\n' \
      "$PROTONPATH" >&2
    return 1
  fi
  realpath -e -- "$resolved"
}

# Prints the newest Wine Mono support installer bundled with the given
# Proton. Some Proton releases bundle Mono without registering it in
# default_pfx.
find_wine_mono_msi() {
  local installers=( "$1"/{files,dist}/share/wine/mono/wine-mono*/support/winemono-support.msi )
  if (( ${#installers[@]} == 0 )); then
    printf 'Wine Mono support installer not found in Proton: %s\n' "$1" >&2
    return 1
  fi
  realpath -e -- "$(newest_by_version "${installers[@]}")"
}

ensure_dotnet_runtime() {
  local listing32 listing64 proton_dir mono_msi
  # NET Framework Setup itself is absent from fresh prefixes.
  local software_key='HKEY_LOCAL_MACHINE\Software\Microsoft'
  local dotnet_key="$software_key\NET Framework Setup\NDP\v4"

  # The packaged Squirrel installer is 32-bit and requires the Full profile.
  listing32="$(list_registry_tree "$software_key" /reg:32)" || exit
  if is_supported_dotnet_release "$(registry_value "$listing32" "$dotnet_key\Full" Release)"; then
    return
  fi

  # Do not install Mono over an existing native .NET installation,
  # including Client-only and 64-bit-only registrations.
  listing64="$(list_registry_tree "$software_key" /reg:64)" || exit
  if registry_has_key "$listing32" "$dotnet_key" || registry_has_key "$listing64" "$dotnet_key"; then
    printf '%s\n' \
      'The existing .NET Framework registration is older than 4.5.2 or incomplete.' \
      'Repair that runtime or use a fresh EVE_WINEPREFIX before running --install.' >&2
    exit 1
  fi

  proton_dir="$(resolve_proton_dir)" || exit
  mono_msi="$(find_wine_mono_msi "$proton_dir")" || exit
  printf 'Installing Wine Mono support from %s in %s\n' "$mono_msi" "$WINEPREFIX"
  run_wine_tool msiexec /i "Z:${mono_msi//\//\\}" /qn /norestart

  listing32="$(list_registry_tree "$software_key" /reg:32)" || exit
  if ! is_supported_dotnet_release "$(registry_value "$listing32" "$dotnet_key\Full" Release)"; then
    printf 'Wine Mono did not register .NET Framework support in %s\n' "$WINEPREFIX" >&2
    exit 1
  fi
}

# Prints the stored GrabPointer value, or nothing if it is unset.
read_grab_pointer() {
  local listing
  listing="$(list_registry_tree 'HKEY_CURRENT_USER\Software\Wine')" || return
  registry_value "$listing" 'HKEY_CURRENT_USER\Software\Wine\X11 Driver' GrabPointer
}

configure_grab_pointer() {
  local stored

  if [[ -z "$grab_pointer" ]]; then
    return
  fi
  stored="$(read_grab_pointer)" || exit
  if [[ "$stored" == "$grab_pointer" ]]; then
    return
  fi

  run_wine_tool reg add 'HKEY_CURRENT_USER\Software\Wine\X11 Driver' \
    /v GrabPointer /t REG_SZ /d "$grab_pointer" /f
  # Check the stored value because UMU can mask reg.exe failures.
  stored="$(read_grab_pointer)" || exit
  if [[ "$stored" != "$grab_pointer" ]]; then
    printf 'Unable to set GrabPointer=%s in %s\n' "$grab_pointer" "$WINEPREFIX" >&2
    exit 1
  fi
}

use_launcher_override() {
  if [[ "$EVE_LAUNCHER_EXE" != /* || ! -f "$EVE_LAUNCHER_EXE" ]]; then
    printf 'EVE_LAUNCHER_EXE must be an absolute path to an existing file: %s\n' \
      "$EVE_LAUNCHER_EXE" >&2
    exit 2
  fi
  launcher_exe="$(realpath -e -- "$EVE_LAUNCHER_EXE")"
  launcher_workdir="$(dirname "$launcher_exe")"
}

discover_launcher() {
  local root version_exe newest_exe
  local active_versions=()

  # Check Proton's steamuser profile before any other Windows user.
  for root in \
    "$WINEPREFIX"/drive_c/users/steamuser/AppData/Local/eve-online \
    "$WINEPREFIX"/drive_c/users/!(steamuser)/AppData/Local/eve-online; do
    active_versions=()
    for version_exe in "$root"/app-[0-9]*/eve-online.exe; do
      # Globs also match directories and broken symlinks.
      if [[ -f "$version_exe" && ! -e "$(dirname "$version_exe")/.dead" ]]; then
        active_versions+=( "$version_exe" )
      fi
    done

    if (( ${#active_versions[@]} > 0 )); then
      newest_exe="$(newest_by_version "${active_versions[@]}")"
      launcher_workdir="$(dirname "$newest_exe")"
      launcher_exe="$newest_exe"
      if [[ -f "$root/eve-online.exe" ]]; then
        launcher_exe="$root/eve-online.exe"
      fi
      return 0
    fi

    if [[ -f "$root/eve-online.exe" ]]; then
      launcher_workdir="$root"
      launcher_exe="$root/eve-online.exe"
      return 0
    fi
  done

  return 1
}

if [[ "${1:-}" == --help || "${1:-}" == -h ]]; then
  show_help
  exit 0
fi

grab_pointer="${EVE_GRAB_POINTER-$default_grab_pointer}"
case "$grab_pointer" in
  ""|Y|N) ;;
  *)
    printf 'EVE_GRAB_POINTER must be Y, N, or empty: %s\n' "$grab_pointer" >&2
    exit 2
    ;;
esac

WINEPREFIX="${EVE_WINEPREFIX:-$default_prefix}"
if [[ "$WINEPREFIX" != /* ]]; then
  printf 'EVE_WINEPREFIX must be an absolute path: %s\n' "$WINEPREFIX" >&2
  exit 2
fi
WINEPREFIX="$(realpath -m -- "$WINEPREFIX")"
export WINEPREFIX
export STEAM_COMPAT_INSTALL_PATH="$WINEPREFIX"

apply_package_environment
export PROTONPATH="${PROTONPATH:-$packaged_proton}"

case "${1:-}" in
  --install)
    shift
    mkdir -p "$WINEPREFIX"
    cd "$WINEPREFIX"
    ensure_dotnet_runtime
    configure_grab_pointer
    exec umu-run "$installer" "$@"
    ;;
  *)
    if [[ -n "${EVE_LAUNCHER_EXE:-}" ]]; then
      use_launcher_override
    elif ! discover_launcher; then
      printf 'CCP launcher not found in Wine prefix: %s\n' "$WINEPREFIX" >&2
      printf '%s\n' \
        'Run eve-online --install or set EVE_LAUNCHER_EXE to its absolute path.' >&2
      exit 1
    fi
    cd "$launcher_workdir"
    configure_grab_pointer
    exec umu-run "$launcher_exe" --product=eve-online "$@"
    ;;
esac
